- name: Fetch and run Poetry installer script
  shell: |
    if ! ~/.local/bin/poetry --version | grep -q '{{ poetry_version }}$'; then
      curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3 - --version {{ poetry_version }}

      if ! ~/.local/bin/poetry --version | grep -q '{{ poetry_version }}$'; then
        exit 1
      else
        echo status=changed
      fi
    fi
  register: task
  changed_when: "'status=changed' in task.stdout"

- name: Add to path via shell config script
  blockinfile:
    path: ~/.profile
    insertafter: EOF
    state: present
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }} :: PATH"
    block: |
      export PATH="~/.local/bin:$PATH"
