- name: Download poetry installer
  get_url:
    url="https://install.python-poetry.org"
    dest="/home/{{ ansible_env.USER }}/Downloads/poetry_installer.py"

- name: Install poetry
  ansible.builtin.command: "python3 /home/{{ ansible_env.USER }}/Downloads/poetry_installer.py"
  args:
    creates: "/home/{{ ansible_env.USER }}/.local/bin/poetry"

- name: Add to path via shell config script
  blockinfile:
    path: "/home/{{ ansible_env.USER }}/.profile"
    insertafter: EOF
    state: present
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }} :: PATH"
    block: |
      export PATH="/home/{{ ansible_env.USER }}/.local/bin:$PATH"

- name: Enable tab completion for Bash
  shell: |
    export PATH="/home/{{ ansible_env.USER }}/.local/bin:$PATH"
    poetry completions bash | sudo tee -a /etc/bash_completion.d/poetry.bash-completion > /dev/null
  changed_when: "'a' in 'b'"

- name: Get poetry version
  ansible.builtin.shell: poetry --version

- name: Print return information from the previous task
  ansible.builtin.debug:
    msg:
      - "Poetry version {{result}}"
